# Generated by Django 6.0.5 on 2026-05-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('language', models.CharField(choices=[('telugu', 'Telugu'), ('sunday_telugu', 'Sunday School Telugu'), ('sunday_hindi', 'Sunday School Hindi'), ('sunday_english', 'Sunday School English')], default='telugu', max_length=20)),
                ('first_letter', models.CharField(max_length=10)),
                ('telugu_lyrics', models.TextField(blank=True)),
                ('english_lyrics', models.TextField(blank=True)),
                ('powerpoint_slides', models.TextField(blank=True)),
                ('audio_video', models.TextField(blank=True)),
                ('chords', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='songs/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wp_post_id', models.IntegerField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='songs.songcategory')),
            ],
        ),
    ]
