# Generated by Django 4.2.30 on 2026-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hindi_lyrics',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('telugu', 'Telugu'), ('sunday_telugu', 'Sunday School Telugu'), ('others', 'Others'), ('sunday_hindi', 'Sunday School Hindi'), ('sunday_english', 'Sunday School English')], default='telugu', max_length=20),
        ),
    ]
