# Generated by Django 6.0.5 on 2026-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_hindi_lyrics_alter_song_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
