# Generated by Django 5.2.10 on 2026-06-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_activity_belief_bibleresource_heroitem_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.CharField(choices=[('Infographics', 'Infographics'), ('Maps', 'Maps'), ('Resource Stories', 'Resource Stories'), ('Downloads', 'Downloads'), ('Genealogies', 'Genealogies'), ('Missionary Stories', 'Missionary Stories'), ('Old Testament', 'Old Testament Stories'), ('New Testament', 'New Testament Stories'), ('Topical', 'Topical Lessons'), ('Biographical', 'Biographical Stories'), ('Pre School', 'Pre School Lessons'), ('Coloring', 'Coloring Activities'), ('Puzzles', 'Bible Puzzles'), ('Quizzes', 'Bible Quizzes')], max_length=50)),
                ('link', models.CharField(blank=True, help_text='URL or file path', max_length=500)),
                ('second_link', models.CharField(blank=True, help_text='Secondary URL or file path (optional)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
