# Generated by Django 6.0.5 on 2026-06-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_activity_belief_bibleresource_heroitem_sitesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Software', 'Software'), ('PPT', 'PPT')], default='Software', max_length=50)),
                ('file', models.FileField(upload_to='downloads/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Resource Download',
                'verbose_name_plural': 'Resource Downloads',
                'ordering': ['order'],
            },
        ),
    ]
