# Generated by Django 6.0.5 on 2026-06-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_resourcedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('month_year', models.CharField(help_text='e.g. May 2026', max_length=100)),
                ('language', models.CharField(default='Telugu', max_length=100)),
                ('cover_image', models.FileField(upload_to='magazines/covers/')),
                ('file', models.FileField(upload_to='magazines/files/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Magazine',
                'verbose_name_plural': 'Magazines',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
