# Generated by Django 6.0.5 on 2026-06-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contentitem'),
        ('pages', '0004_magazine'),
    ]

    operations = [
    ]
