# Generated by Django 6.0.6 on 2026-07-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_magazine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('section', models.CharField(max_length=100)),
                ('page_category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
