# Generated by Django 6.0.6 on 2026-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_contentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='pdf_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
