# Generated by Django 6.0.5 on 2026-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_merge_0003_contentitem_0004_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='page_category',
            field=models.CharField(blank=True, help_text='Top level category like Bible Maps, Bible Infographics, etc.', max_length=100, null=True),
        ),
    ]
