# Generated by Django 6.0.5 on 2026-06-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contentitem_page_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='link',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='second_link',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image',
            field=models.CharField(blank=True, help_text='Path to image for things like Missionary Stories', max_length=500),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='Array of links, e.g. [{"text": "PDF", "url": "/path"}]'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='section',
            field=models.CharField(help_text='Sub-section name, e.g. New Testament Maps', max_length=100),
        ),
    ]
