# Generated by Django 6.0.5 on 2026-06-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_contentitem_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='image',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='cover_image',
            field=models.FileField(blank=True, help_text='Direct image upload', null=True, upload_to='resources/covers/'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Path to image or external URL', max_length=500),
        ),
    ]
