# Generated by Django 6.0.5 on 2026-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_contentitem_image_contentitem_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='subtitle',
            field=models.CharField(blank=True, help_text='E.g. Scripture Reference', max_length=255),
        ),
    ]
