# Generated by Django 6.0.5 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contentitem_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
