# Generated by Django 5.2.10 on 2026-07-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contentitem_pdf_url'),
        ('pages', '0010_magazine_is_active'),
    ]

    operations = [
    ]
