# Generated by Django 6.0.5 on 2026-07-06 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_merge_20260702_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Content Item', 'verbose_name_plural': 'Content Items'},
        ),

        migrations.AddField(
            model_name='contentitem',
            name='cover_image',
            field=models.FileField(blank=True, help_text='Direct image upload', null=True, upload_to='resources/covers/'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentitem',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='Array of links, e.g. [{"text": "PDF", "url": "/path"}]'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='image_url',
            field=models.CharField(blank=True, help_text='Path to image or external URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='page_category',
            field=models.CharField(blank=True, help_text='Top level category like Bible Maps, Bible Infographics, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='section',
            field=models.CharField(help_text='Sub-section name, e.g. New Testament Maps', max_length=100),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='subtitle',
            field=models.CharField(blank=True, help_text='E.g. Scripture Reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='resourcedownload',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('PPT', 'PPT'), ('PDF', 'PDF')], default='Software', max_length=50),
        ),
    ]
