# Generated by Django 6.0.5 on 2026-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_contentitem_options_remove_contentitem_pdf_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentitem',
            name='pdf_url',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='pdf_document',
            field=models.FileField(blank=True, help_text='Upload a PDF document for this story', null=True, upload_to='stories/pdfs/'),
        ),
    ]
